### ISSUE TITLE
texture change under biome doesn't work

### ISSUE THREAD

**Issue by Bradlu378** [opekope2/OptiGUI#35] opened 2023-04-17 15:54 UTC
I have a texture pack that changes the animated image depending on the biome, but reproduces only the standard.
I have attached the file of this texture pack.
On optifine everything works and I really wish that this function was also in OptiGUI

[[Dark] Animated Fox Gui - Ekuzen & oakar258.zip](https://github.com/opekope2/OptiGUI-Next/files/11252742/Dark.Animated.Fox.Gui.-.Ekuzen.oakar258.zip)

**Comment by opekope2** [comment] 2023-04-17 16:39
Does it work with OptiGUI+Animatica?

**Comment by Bradlu378** [comment] 2023-04-18 20:38
only standard animation that does not change depending on the biome

**Comment by Bradlu378** [comment] 2023-04-18 20:39
![image](https://user-images.githubusercontent.com/119012794/232899597-37cf3d38-08cc-4286-a2ae-c0dd74e0dcd4.png)

standart animation without biome/world checks

**Comment by opekope2** [comment] 2023-04-19 20:17
Can confirm, it's not "loading order".
This code is being rewritten as part of #32. With the new code, it will be easier to track if something is not configured correctly. I'll make sure to test this resource pack before releasing beta 4.

**Comment by Bradlu378** [comment] 2023-04-19 20:22
Thanks, I'll be waiting for this update.

**Comment by opekope2** [comment] 2023-04-19 20:37
Please keep the issue open until the fix actually gets merged, so I don't accidentally forget about it.

**Comment by Bradlu378** [comment] 2023-04-19 21:44
ok, i'll keep it in mind

**Comment by opekope2** [comment] 2023-05-04 02:12
That resource pack behaves differently from my expectations, tho it works on OptiFine, so I'll fix OptiGUI.

**Closed as completed** 2023-05-17 19:45 UTC

**Comment by Rozbiynk** [comment] 2023-06-04 12:08
is update inside inventory possible? for example, it change texture depending on the biome only when i reopen my inventory. Is it possible to doesnt reopen it? its can reproduce is you have invmove mod or flying on elytra through biome

**Comment by opekope2** [comment] 2023-06-04 12:27
Yes I know that this happens, because of optimizations, I partially fixed it locally tho, will push it sometime when I'm done (the code change is also needed for the book GUI)

**Comment by opekope2** [comment] 2023-06-07 12:38
Now it updates every game tick. Will be released hopefully today with the full 2.1.0 release (after 1.20 loom mappings are available)
