### ISSUE TITLE
[CRASH] Game Launch - Conflict with Cobblemon

### ISSUE THREAD

**Issue by nasapierce** [opekope2/OptiGUI#105] opened 2024-07-13 18:45 UTC
### Loader and its version

Fabric Loader 0.15.11

### OptiGUI version

Optigui 2.1.7

### Steps to reproduce

Launch.
Crash.

### Game logs

```
[13:32:09] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[13:32:09] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[13:32:09] [main/WARN]: Warnings were found!
 - Mod 'OptiGUI' (optigui) 2.1.7 recommends any version of animatica, which is missing!
	 - You should install any version of animatica for the optimal experience.
[13:32:09] [main/INFO]: Loading 74 mods:
	- cobblemon 1.5.2+1.20.1
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 17
	- minecraft 1.20.1
	- optigui 2.1.7
	   |-- optiglue 2.1.7-mc.1.19.3
	   |-- org_apache_commons_commons-text 1.10.0
	   \-- org_ini4j_ini4j 0.5.4
[13:32:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:32:13] [main/INFO]: Compatibility level set to JAVA_17
[13:32:13] [main/WARN]: Error loading class: juuxel/adorn/block/variant/BlockVariantSets (java.lang.ClassNotFoundException: juuxel/adorn/block/variant/BlockVariantSets)
[13:32:13] [main/WARN]: @Mixin target juuxel.adorn.block.variant.BlockVariantSets was not found mixins.cobblemon-common.json:invoker.AdornRegisterInvoker from mod cobblemon
[13:32:14] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[13:32:14] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[13:32:17] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 89 milliseconds
[13:32:19] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:32:19] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[13:32:19] [Render thread/INFO]: Booting LaxPermissionValidator, permissions will be checked using Minecrafts permission level system, see https://minecraft.fandom.com/wiki/Permission_level
[13:32:19] [Render thread/INFO]: Launching Cobblemon 1.5.2 
[13:32:19] [Render thread/ERROR]: No data fixer registered for cobblemon:pokemon
[13:32:19] [Render thread/ERROR]: No data fixer registered for cobblemon:empty_pokeball
[13:32:19] [Render thread/ERROR]: No data fixer registered for cobblemon:boat
[13:32:19] [Render thread/ERROR]: No data fixer registered for cobblemon:chest_boat
[13:32:19] [Render thread/ERROR]: No data fixer registered for cobblemon:generic_bedrock
[13:32:19] [Render thread/INFO]: Starting the Best Spawner...
[13:32:19] [Render thread/INFO]: Loaded 5 spawning condition types.
[13:32:19] [Render thread/INFO]: Loaded 5 spawning context types.
[13:32:19] [Render thread/INFO]: Loaded 1 spawn detail types.
[13:32:20] [Cobblemon Showdown/INFO]: Starting showdown service...
[13:32:24] [Cobblemon Showdown/INFO]: Showdown has been started!
[13:32:24] [Render thread/INFO]: Note: Cobblemon data registries are only loaded once per server instance as Pok�mon species are not safe to reload.
[13:32:24] [Render thread/INFO]: Registered the cobblemon:species_features registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:global_species_features registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:species_feature_assignments registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:action_effects registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:moves registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:abilities registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:species registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:species_additions registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:pokeballs registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:properties_tab_completion registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:spawn_detail_presets registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:spawn_rules registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:mechanics registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:bag_items registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:dialogues registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:natural_materials registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:fossils registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:spawn_pool_world registry
[13:32:24] [Render thread/INFO]: Registered the cobblemon:berries registry
[13:32:24] [Render thread/INFO]: Initializing Cobblemon client
[13:32:24] [Render thread/INFO]: Registering Pok�mon renderer
[13:32:24] [Render thread/INFO]: Registering Pok�Ball renderer
[13:32:24] [Render thread/INFO]: Registering Boat renderer
[13:32:24] [Render thread/INFO]: Registering Boat with Chest renderer
[13:32:24] [Render thread/INFO]: Registering Generic Bedrock Entity renderer
[13:32:24] [Render thread/INFO]: Registering custom BuiltinItemRenderers
[13:32:24] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
```

### Anything else

Only things in the load order are
Cobblemon 1.5.2
Fabric API 0.92.2
Kotlin 2.0.0
OptiGUI 2.1.7

I have opened an issue on Cobblemon's repo as well.

**Comment by opekope2** [comment] 2024-07-13 21:52
Duplicate of #100
You should report this at https://github.com/FabricMC/fabric-language-kotlin

**Closed as not planned by opekope2** 2024-07-13 21:52 UTC
Labels: crash

**Comment by opekope2** [comment] 2024-07-25 19:31
Cobblemon bundles Kotlin 1.8.20 for some reason instead of depending on FLK or JAR-in-JAR'ing it. This causes serious compatibility issues. Download a matching version of Fabric Language Kotlin (the one with Kotlin 1.8.22 seems to work).
